alias spell="cd ~/Documents/SPELL/spell && pipenv shell"
alias gst="git status"
alias gdf="git diff"
alias tm="tmux attach -t work || tmux new -s work"
alias djsh="python manage.py shell"
alias djrun="python manage.py runserver"
alias nrs="npm run serve"
