-- [nfnl] Compiled from fnl/m3xan1k/keymap.fnl by https://github.com/Olical/nfnl, do not edit.
local opts = {noremap = true, silent = true}
vim.keymap.set("", "<Space>", "<Nop>", opts)
vim.keymap.set("", ",", "<Nop>", opts)
vim.g.mapleader = " "
vim.g.maplocalleader = ","
vim.keymap.set("i", "jk", "<ESC>", opts)
vim.keymap.set("n", "<A-j>", ":m .+1<CR>==", opts)
vim.keymap.set("n", "<A-k>", ":m .-2<CR>==", opts)
vim.keymap.set("v", "<A-j>", ":m '>+1<CR>gv=gv", opts)
vim.keymap.set("v", "<A-k>", ":m '<-2<CR>gv=gv", opts)
vim.keymap.set("x", "<leader>p", "\"_dP", opts)
vim.keymap.set("v", "p", "\"_dP", opts)
vim.keymap.set("n", "<leader>y", "\"+y", opts)
vim.keymap.set("v", "<leader>y", "\"+y", opts)
vim.keymap.set("n", "<leader>Y", "\"+Y", opts)
vim.keymap.set("n", "<leader>d", "\"_d", opts)
vim.keymap.set("v", "<leader>d", "\"_d", opts)
vim.keymap.set("n", "Q", "<nop>", opts)
vim.keymap.set("n", "<leader>rk", ":resize -2<CR>", opts)
vim.keymap.set("n", "<leader>rj", ":resize +2<CR>", opts)
vim.keymap.set("n", "<leader>rh", ":vertical resize -2<CR>", opts)
vim.keymap.set("n", "<leader>rl", ":vertical resize +2<CR>", opts)
vim.keymap.set("v", "<", "<gv", opts)
vim.keymap.set("v", ">", ">gv", opts)
vim.keymap.set("n", "<leader>e", ":NERDTreeToggle<CR>", opts)
vim.keymap.set("n", "<leader>bk", ":bdelete!<CR>", opts)
vim.keymap.set("n", "<leader>nh", ":noh<CR>", opts)
vim.keymap.set("n", "<C-h>", ":BufferLineCyclePrev<CR>", opts)
vim.keymap.set("n", "<C-l>", ":BufferLineCycleNext<CR>", opts)
vim.keymap.set("n", "<C-A-h>", ":BufferLineMovePrev<CR>", opts)
vim.keymap.set("n", "<C-A-l>", ":BufferLineMoveNext<CR>", opts)
vim.keymap.set("n", "<leader>ws", ":split<CR>", opts)
vim.keymap.set("n", "<leader>wv", ":vsplit<CR>", opts)
vim.keymap.set("n", "<leader>wn", ":new<CR>", opts)
vim.keymap.set("n", "<leader>wc", ":close!<CR>", opts)
vim.keymap.set("n", "<leader>wh", ":wincmd h<CR>", opts)
vim.keymap.set("n", "<leader>wl", ":wincmd l<CR>", opts)
vim.keymap.set("n", "<leader>wj", ":wincmd j<CR>", opts)
vim.keymap.set("n", "<leader>wk", ":wincmd k<CR>", opts)
vim.keymap.set("n", "<leader>gt", ":A<CR>", opts)
vim.cmd("let @i = 'import IPython; IPython.embed()'")
vim.cmd("let @p = 'from pprint import pprint; pprint()'")
return {}
